name: Rancher Deploy Action
description: Deploy into Rancher Cluster
author: DA Team <da.team@sherwin.com>
inputs:    
   labels_path:
    description: 'Location of kubernetes labels'
    required: false
    default: 'kubernetes/labels'
   deployment_yaml_path:
     description: 'Location of the deployment.yml file'
     required: false
     default: 'kubernetes/deployment.yml'
   namespace:
     description: 'Rancher namespace'
     required: true
     default: 'gitactions'
   files:
     description: 'Kubernetes files to apply'
     required: false
     default: 'kubernetes/.'
   environment:
     descripton: 'dev, prod'
     required: true
   kube_config_data:
     description: 'Kube config for rancher cluster'
     required: true
   jf_artifactory_token:
     description: 'Artifactory Auth Token'
     required: true
     
runs:
  using: "composite"
  steps:
#      - name: Read labels file contents
#        id: read_labels
#        uses: andstor/file-reader-action@v1
#        with:
#          path: ${{ inputs.labels_path }}

# #      - name: File contents
# #        run: echo "${{ steps.read_labels.outputs.contents }}"
# #        shell: bash

# #      - name: Replace labels
# #        uses: jacobtomlinson/gha-find-replace@master
# #        with:
# #          find: "@LABELS" 
# #          replace: ${{ steps.read_label.outputs.contents }}
# #          include: ${{ inputs.deployment_yamp_path }}

#      - name: Docker image promote 
#        uses: sherwin-williams-co/sw-promote-docker-image-action@main
#        if: ${{ github.event.inputs.ENV != 'dev' }}
#        with:
#          environment: ${{ github.event.inputs.ENV }}
#          image_name: ${{ github.event.inputs.IMAGE_NAME }}
#          image_tag: ${{ github.event.inputs.TAG }}
#          artifactory_secret: ${{ inputs.jf_artifactory_token }}

     - name: Deploy to rancher cluster
       uses: sherwin-williams-co/sw-rancher-deploy-action@master
       env:
         KUBE_CONFIG_DATA: ${{ inputs.kube_config_data }}
       with:
         namespace: "${{ inputs.environment }}-${{ inputs.namespace }}"
         files: "-f ${{ inputs.files }}"
        
        
branding:
  icon: git-branch
  color: white
